# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call('testfuns_rcpp_hello_world', PACKAGE = 'testfuns')
}

timesTwo <- function(x) {
    .Call('testfuns_timesTwo', PACKAGE = 'testfuns', x)
}

squared <- function(x) {
    .Call('testfuns_squared', PACKAGE = 'testfuns', x)
}

