// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP EcoHydro2D_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(rcpp_hello_world());
    return __result;
END_RCPP
}
// Soil_cpp
List Soil_cpp(std::string stype);
RcppExport SEXP EcoHydro2D_Soil_cpp(SEXP stypeSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type stype(stypeSEXP);
    __result = Rcpp::wrap(Soil_cpp(stype));
    return __result;
END_RCPP
}
// zeta
double zeta(double s, double s_star, double s_w, double q);
RcppExport SEXP EcoHydro2D_zeta(SEXP sSEXP, SEXP s_starSEXP, SEXP s_wSEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type s(sSEXP);
    Rcpp::traits::input_parameter< double >::type s_star(s_starSEXP);
    Rcpp::traits::input_parameter< double >::type s_w(s_wSEXP);
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    __result = Rcpp::wrap(zeta(s, s_star, s_w, q));
    return __result;
END_RCPP
}
// WB_fun_cpp
List WB_fun_cpp(List vegpar_in, double In, double last_t_soil_sat, List soilpar_in, double Zmean_in, double deltat, double Z_prev, double Z_in);
RcppExport SEXP EcoHydro2D_WB_fun_cpp(SEXP vegpar_inSEXP, SEXP InSEXP, SEXP last_t_soil_satSEXP, SEXP soilpar_inSEXP, SEXP Zmean_inSEXP, SEXP deltatSEXP, SEXP Z_prevSEXP, SEXP Z_inSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< List >::type vegpar_in(vegpar_inSEXP);
    Rcpp::traits::input_parameter< double >::type In(InSEXP);
    Rcpp::traits::input_parameter< double >::type last_t_soil_sat(last_t_soil_satSEXP);
    Rcpp::traits::input_parameter< List >::type soilpar_in(soilpar_inSEXP);
    Rcpp::traits::input_parameter< double >::type Zmean_in(Zmean_inSEXP);
    Rcpp::traits::input_parameter< double >::type deltat(deltatSEXP);
    Rcpp::traits::input_parameter< double >::type Z_prev(Z_prevSEXP);
    Rcpp::traits::input_parameter< double >::type Z_in(Z_inSEXP);
    __result = Rcpp::wrap(WB_fun_cpp(vegpar_in, In, last_t_soil_sat, soilpar_in, Zmean_in, deltat, Z_prev, Z_in));
    return __result;
END_RCPP
}
// WBEcoHyd
NumericMatrix WBEcoHyd(NumericVector R, NumericVector ETp, CharacterVector vegtype, List soilpar, NumericVector s_init, double fullday, //std::string model, NumericVector Zmean, NumericVector GWdepths, NumericVector GWdepths_prev, double deltat, NumericVector NX, NumericVector NY, int t);
RcppExport SEXP EcoHydro2D_WBEcoHyd(SEXP RSEXP, SEXP ETpSEXP, SEXP vegtypeSEXP, SEXP soilparSEXP, SEXP s_initSEXP, SEXP fulldaySEXP, SEXP modelSEXP, SEXP ZmeanSEXP, SEXP GWdepthsSEXP, SEXP GWdepths_prevSEXP, SEXP deltatSEXP, SEXP NXSEXP, SEXP NYSEXP, SEXP tSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type R(RSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ETp(ETpSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type vegtype(vegtypeSEXP);
    Rcpp::traits::input_parameter< List >::type soilpar(soilparSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type s_init(s_initSEXP);
    Rcpp::traits::input_parameter< double >::type fullday(fulldaySEXP);
    Rcpp::traits::input_parameter< //std::string >::type model(modelSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Zmean(ZmeanSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type GWdepths(GWdepthsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type GWdepths_prev(GWdepths_prevSEXP);
    Rcpp::traits::input_parameter< double >::type deltat(deltatSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type NX(NXSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type NY(NYSEXP);
    Rcpp::traits::input_parameter< int >::type t(tSEXP);
    __result = Rcpp::wrap(WBEcoHyd(R, ETp, vegtype, soilpar, s_init, fullday, model, Zmean, GWdepths, GWdepths_prev, deltat, NX, NY, t));
    return __result;
END_RCPP
}
