// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// int_test
double int_test(double c1, double z1, double z2);
RcppExport SEXP EcoHydro2D_int_test(SEXP c1SEXP, SEXP z1SEXP, SEXP z2SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type c1(c1SEXP);
    Rcpp::traits::input_parameter< double >::type z1(z1SEXP);
    Rcpp::traits::input_parameter< double >::type z2(z2SEXP);
    __result = Rcpp::wrap(int_test(c1, z1, z2));
    return __result;
END_RCPP
}
// RWU_cpp
double RWU_cpp(double z1, double Zmean, double fs);
RcppExport SEXP EcoHydro2D_RWU_cpp(SEXP z1SEXP, SEXP ZmeanSEXP, SEXP fsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type z1(z1SEXP);
    Rcpp::traits::input_parameter< double >::type Zmean(ZmeanSEXP);
    Rcpp::traits::input_parameter< double >::type fs(fsSEXP);
    __result = Rcpp::wrap(RWU_cpp(z1, Zmean, fs));
    return __result;
END_RCPP
}
// Rc_B_cpp
double Rc_B_cpp(double z1, double z2, double c1, double Zmean, double fs);
RcppExport SEXP EcoHydro2D_Rc_B_cpp(SEXP z1SEXP, SEXP z2SEXP, SEXP c1SEXP, SEXP ZmeanSEXP, SEXP fsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type z1(z1SEXP);
    Rcpp::traits::input_parameter< double >::type z2(z2SEXP);
    Rcpp::traits::input_parameter< double >::type c1(c1SEXP);
    Rcpp::traits::input_parameter< double >::type Zmean(ZmeanSEXP);
    Rcpp::traits::input_parameter< double >::type fs(fsSEXP);
    __result = Rcpp::wrap(Rc_B_cpp(z1, z2, c1, Zmean, fs));
    return __result;
END_RCPP
}
// E_Teuling_cpp
double E_Teuling_cpp(double s, List vegpar);
RcppExport SEXP EcoHydro2D_E_Teuling_cpp(SEXP sSEXP, SEXP vegparSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type s(sSEXP);
    Rcpp::traits::input_parameter< List >::type vegpar(vegparSEXP);
    __result = Rcpp::wrap(E_Teuling_cpp(s, vegpar));
    return __result;
END_RCPP
}
// G_cpp
double G_cpp(double b, double hb, double Z);
RcppExport SEXP EcoHydro2D_G_cpp(SEXP bSEXP, SEXP hbSEXP, SEXP ZSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type hb(hbSEXP);
    Rcpp::traits::input_parameter< double >::type Z(ZSEXP);
    __result = Rcpp::wrap(G_cpp(b, hb, Z));
    return __result;
END_RCPP
}
// m_fun
NumericVector m_fun(List vegpar_i, List soilpar_i, double Z_in, double Gin);
RcppExport SEXP EcoHydro2D_m_fun(SEXP vegpar_iSEXP, SEXP soilpar_iSEXP, SEXP Z_inSEXP, SEXP GinSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< List >::type vegpar_i(vegpar_iSEXP);
    Rcpp::traits::input_parameter< List >::type soilpar_i(soilpar_iSEXP);
    Rcpp::traits::input_parameter< double >::type Z_in(Z_inSEXP);
    Rcpp::traits::input_parameter< double >::type Gin(GinSEXP);
    __result = Rcpp::wrap(m_fun(vegpar_i, soilpar_i, Z_in, Gin));
    return __result;
END_RCPP
}
// rho_new_cpp
NumericVector rho_new_cpp(double s, double ZZ, List soilpar, List vegpar, double Z_mean, double Z_prev);
RcppExport SEXP EcoHydro2D_rho_new_cpp(SEXP sSEXP, SEXP ZZSEXP, SEXP soilparSEXP, SEXP vegparSEXP, SEXP Z_meanSEXP, SEXP Z_prevSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type s(sSEXP);
    Rcpp::traits::input_parameter< double >::type ZZ(ZZSEXP);
    Rcpp::traits::input_parameter< List >::type soilpar(soilparSEXP);
    Rcpp::traits::input_parameter< List >::type vegpar(vegparSEXP);
    Rcpp::traits::input_parameter< double >::type Z_mean(Z_meanSEXP);
    Rcpp::traits::input_parameter< double >::type Z_prev(Z_prevSEXP);
    __result = Rcpp::wrap(rho_new_cpp(s, ZZ, soilpar, vegpar, Z_mean, Z_prev));
    return __result;
END_RCPP
}
// Fun_E_cpp
NumericVector Fun_E_cpp(double s, double Z, List soilpar, List vegpar);
RcppExport SEXP EcoHydro2D_Fun_E_cpp(SEXP sSEXP, SEXP ZSEXP, SEXP soilparSEXP, SEXP vegparSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type s(sSEXP);
    Rcpp::traits::input_parameter< double >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< List >::type soilpar(soilparSEXP);
    Rcpp::traits::input_parameter< List >::type vegpar(vegparSEXP);
    __result = Rcpp::wrap(Fun_E_cpp(s, Z, soilpar, vegpar));
    return __result;
END_RCPP
}
// Fun_FB_cpp
NumericVector Fun_FB_cpp(double s, List soilpar, List vegpar, double Z, double Zmean);
RcppExport SEXP EcoHydro2D_Fun_FB_cpp(SEXP sSEXP, SEXP soilparSEXP, SEXP vegparSEXP, SEXP ZSEXP, SEXP ZmeanSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type s(sSEXP);
    Rcpp::traits::input_parameter< List >::type soilpar(soilparSEXP);
    Rcpp::traits::input_parameter< List >::type vegpar(vegparSEXP);
    Rcpp::traits::input_parameter< double >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< double >::type Zmean(ZmeanSEXP);
    __result = Rcpp::wrap(Fun_FB_cpp(s, soilpar, vegpar, Z, Zmean));
    return __result;
END_RCPP
}
// FB_new_cpp
NumericVector FB_new_cpp(double s, List soilpar_in, List vegpar_in, double Zfb, double Zmean, double Z_prev);
RcppExport SEXP EcoHydro2D_FB_new_cpp(SEXP sSEXP, SEXP soilpar_inSEXP, SEXP vegpar_inSEXP, SEXP ZfbSEXP, SEXP ZmeanSEXP, SEXP Z_prevSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type s(sSEXP);
    Rcpp::traits::input_parameter< List >::type soilpar_in(soilpar_inSEXP);
    Rcpp::traits::input_parameter< List >::type vegpar_in(vegpar_inSEXP);
    Rcpp::traits::input_parameter< double >::type Zfb(ZfbSEXP);
    Rcpp::traits::input_parameter< double >::type Zmean(ZmeanSEXP);
    Rcpp::traits::input_parameter< double >::type Z_prev(Z_prevSEXP);
    __result = Rcpp::wrap(FB_new_cpp(s, soilpar_in, vegpar_in, Zfb, Zmean, Z_prev));
    return __result;
END_RCPP
}
// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP EcoHydro2D_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(rcpp_hello_world());
    return __result;
END_RCPP
}
// Soil_cpp
List Soil_cpp(std::string stype);
RcppExport SEXP EcoHydro2D_Soil_cpp(SEXP stypeSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type stype(stypeSEXP);
    __result = Rcpp::wrap(Soil_cpp(stype));
    return __result;
END_RCPP
}
// zeta
double zeta(double s, double s_star, double s_w, double q);
RcppExport SEXP EcoHydro2D_zeta(SEXP sSEXP, SEXP s_starSEXP, SEXP s_wSEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type s(sSEXP);
    Rcpp::traits::input_parameter< double >::type s_star(s_starSEXP);
    Rcpp::traits::input_parameter< double >::type s_w(s_wSEXP);
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    __result = Rcpp::wrap(zeta(s, s_star, s_w, q));
    return __result;
END_RCPP
}
// WB_fun_cpp
List WB_fun_cpp(List vegpar_in, double In, double last_t_soil_sat, List soilpar_in, double Zmean_in, int deltat, double Z_prev, double Z_in);
RcppExport SEXP EcoHydro2D_WB_fun_cpp(SEXP vegpar_inSEXP, SEXP InSEXP, SEXP last_t_soil_satSEXP, SEXP soilpar_inSEXP, SEXP Zmean_inSEXP, SEXP deltatSEXP, SEXP Z_prevSEXP, SEXP Z_inSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< List >::type vegpar_in(vegpar_inSEXP);
    Rcpp::traits::input_parameter< double >::type In(InSEXP);
    Rcpp::traits::input_parameter< double >::type last_t_soil_sat(last_t_soil_satSEXP);
    Rcpp::traits::input_parameter< List >::type soilpar_in(soilpar_inSEXP);
    Rcpp::traits::input_parameter< double >::type Zmean_in(Zmean_inSEXP);
    Rcpp::traits::input_parameter< int >::type deltat(deltatSEXP);
    Rcpp::traits::input_parameter< double >::type Z_prev(Z_prevSEXP);
    Rcpp::traits::input_parameter< double >::type Z_in(Z_inSEXP);
    __result = Rcpp::wrap(WB_fun_cpp(vegpar_in, In, last_t_soil_sat, soilpar_in, Zmean_in, deltat, Z_prev, Z_in));
    return __result;
END_RCPP
}
// WBEcoHyd
NumericMatrix WBEcoHyd(int x, int y, int t, NumericVector R, NumericVector ETp, CharacterVector vtype, List soilpar, NumericVector s_init, double fullday, NumericVector Zmean, NumericVector GWdepths, NumericVector GWdepths_prev, int deltat, NumericVector NX, NumericVector NY);
RcppExport SEXP EcoHydro2D_WBEcoHyd(SEXP xSEXP, SEXP ySEXP, SEXP tSEXP, SEXP RSEXP, SEXP ETpSEXP, SEXP vtypeSEXP, SEXP soilparSEXP, SEXP s_initSEXP, SEXP fulldaySEXP, SEXP ZmeanSEXP, SEXP GWdepthsSEXP, SEXP GWdepths_prevSEXP, SEXP deltatSEXP, SEXP NXSEXP, SEXP NYSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type t(tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type R(RSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ETp(ETpSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type vtype(vtypeSEXP);
    Rcpp::traits::input_parameter< List >::type soilpar(soilparSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type s_init(s_initSEXP);
    Rcpp::traits::input_parameter< double >::type fullday(fulldaySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Zmean(ZmeanSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type GWdepths(GWdepthsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type GWdepths_prev(GWdepths_prevSEXP);
    Rcpp::traits::input_parameter< int >::type deltat(deltatSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type NX(NXSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type NY(NYSEXP);
    __result = Rcpp::wrap(WBEcoHyd(x, y, t, R, ETp, vtype, soilpar, s_init, fullday, Zmean, GWdepths, GWdepths_prev, deltat, NX, NY));
    return __result;
END_RCPP
}
