# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

int_test <- function(c1, z1, z2) {
    .Call('EcoHydro2D_int_test', PACKAGE = 'EcoHydro2D', c1, z1, z2)
}

RWU_cpp <- function(z1, Zmean, fs) {
    .Call('EcoHydro2D_RWU_cpp', PACKAGE = 'EcoHydro2D', z1, Zmean, fs)
}

Rc_B_cpp <- function(z1, z2, c1, Zmean, fs) {
    .Call('EcoHydro2D_Rc_B_cpp', PACKAGE = 'EcoHydro2D', z1, z2, c1, Zmean, fs)
}

E_Teuling_cpp <- function(s, vegpar) {
    .Call('EcoHydro2D_E_Teuling_cpp', PACKAGE = 'EcoHydro2D', s, vegpar)
}

G_cpp <- function(b, hb, Z) {
    .Call('EcoHydro2D_G_cpp', PACKAGE = 'EcoHydro2D', b, hb, Z)
}

m_fun <- function(vegpar_i, soilpar_i, Z_in, Gin) {
    .Call('EcoHydro2D_m_fun', PACKAGE = 'EcoHydro2D', vegpar_i, soilpar_i, Z_in, Gin)
}

rho_new_cpp <- function(s, ZZ, soilpar, vegpar, Z_mean, Z_prev) {
    .Call('EcoHydro2D_rho_new_cpp', PACKAGE = 'EcoHydro2D', s, ZZ, soilpar, vegpar, Z_mean, Z_prev)
}

Fun_E_cpp <- function(s, Z, soilpar, vegpar) {
    .Call('EcoHydro2D_Fun_E_cpp', PACKAGE = 'EcoHydro2D', s, Z, soilpar, vegpar)
}

Fun_FB_cpp <- function(s, soilpar, vegpar, Z, Zmean) {
    .Call('EcoHydro2D_Fun_FB_cpp', PACKAGE = 'EcoHydro2D', s, soilpar, vegpar, Z, Zmean)
}

FB_new_cpp <- function(s, soilpar_in, vegpar_in, Zfb, Zmean, Z_prev) {
    .Call('EcoHydro2D_FB_new_cpp', PACKAGE = 'EcoHydro2D', s, soilpar_in, vegpar_in, Zfb, Zmean, Z_prev)
}

rcpp_hello_world <- function() {
    .Call('EcoHydro2D_rcpp_hello_world', PACKAGE = 'EcoHydro2D')
}

Soil_cpp <- function(stype) {
    .Call('EcoHydro2D_Soil_cpp', PACKAGE = 'EcoHydro2D', stype)
}

WBEcoHyd <- function(R, ETp, vegtype, soilpar, s_init, fullday, model, Zmean, GWdepths, GWdepths_prev, deltat, NX, NY, t) {
    .Call('EcoHydro2D_WBEcoHyd', PACKAGE = 'EcoHydro2D', R, ETp, vegtype, soilpar, s_init, fullday, model, Zmean, GWdepths, GWdepths_prev, deltat, NX, NY, t)
}

